# Generated by Django 5.0.6 on 2024-07-11 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0003_item_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="category",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
