# Generated by Django 5.0.6 on 2024-07-11 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0004_remove_item_category_delete_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="quantity",
        ),
    ]
