# Generated by Django 5.0.6 on 2024-07-14 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0007_cart_product_count_cart_total_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="amount",
            field=models.FloatField(default=0.0),
        ),
    ]
