# Generated by Django 5.0.6 on 2024-10-06 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0008_cartitem_amount"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderitem",
            old_name="price",
            new_name="amount",
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="quantity",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
